### ISSUE TITLE
How to Handle Time Series

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave-ml#12]
Currently Driverless AI can "automatically" handle Time Series - in the python client there are 5ish extra parameters that are needed so it's not automatic in the sense that the user has to give extra information. 

* time_period_in_seconds (int) – the length of the time period in seconds, used in timeseries problems
* num_prediction_periods (int) – timeseries forecast horizont in time period units
* num_gap_periods (int) – number of time periods after which forecast starts
* time_groups_columns (List[str]) – list of column names, contributing to time ordering
* unavailable_at_prediction_time_columns (List[str]) – list of column names, which won’t be present at prediction time (server versions >= 1.8.1)

H2O-3 Does not handle forecasting automatically. A decision needs to be made on to either 
1. Don't allow any forecasting
2. Only allow forecasting if folks are using DAI 
3. Augment H2O-3 with something open source like Prophet for forecasting 

1. I think is okay for now because people can always use the DAI client if they really need to

**Comment by geomodular** [comment]
We don't support forecasting for either of the engines, and currently, there is no plan to do it. I'd leave it as an advanced feature that should be done separately using true clients.

MLOps integration is planned for the next release so users can build separately and the resulting model can be used inside WaveML.

Closing, thanks @mtanco!
