### ISSUE TITLE
Q integration support for DAI

### ISSUE THREAD

**Issue by surenH2oai** [h2oai/wave-ml#14]
**Is your feature request related to a problem? Please describe.**
Q need to provide API SDK level support or documentation + tutorial (q tour) for Q applications which need to use DAI (1.9) for authoring new models and refitting.

**Describe the solution you'd like**
We need to either expose the DAI Python client or the native DAI client as part of Q SDK or provide simpler APIs to invoke common DAI operations that are most needed for ML based Q applications.

**Describe alternatives you've considered**
We may just simply only provide documentation and tour/tutorial code snippets on how to do
**Additional context**
Not sure eventually we would need to support H2o-3.

**Comment by geomodular** [comment]
Old issue. WaveML is part of the answer. DAI integration is set for the current milestone.
