### ISSUE TITLE
Text Columns in the Training Dataset

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave-ml#19]
Driverless AI can automatically handle text datasets where as H2O-3 cannot.

- [x] check if h2o-3 fails when given text (small & large) data or uses the data as a categorical column. If it fails then there should be checks for this type of data, if it runs we just need to make sure it's documented that text won't be used in a "smart" way

- [ ] (optional) use Word2Vec (https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/word2vec.html) to pre-process text automatically behind-the-scenes

**Comment by vopani** [comment]
AutoML handles categorical variables internally. So at least model won't fail.

For longer textual data (like reviews or tweets), categorical splits or encoding isn't meaningful and using Word2Vec is at least better. This should be part of the `preprocessing` argument in H2O AutoML (which I believe is WIP but not available yet). I don't think handling it separately (it's just replication) should be in the scope of WaveML.

We should make it clear in documentation.

**Comment by geomodular** [comment]
Thanks, @vopani! Closing the issue.
