### ISSUE TITLE
Auto-Detect Column Type

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave-ml#20]
Driverless AI will automatically detect if a dataset is classification, h2o-3 AutoML will not: it will run regression if the target is 0s and 1s unless the data type is enum. It would be good to handle this automatically for the user and change the data type of the target as appropriate. 

Driverless AI will do this auto-column checking for feature columns as well. The Credit Card dataset has a feature `Sex` with values of `1` and `2` instead of male & female - this could make the model in h2o-3 not as good if it is treating this value as numeric instead of categorical. Maybe automatic data typing should be done on all columns.

Tasks:

- [x] Auto Data Typing for Target Column (this is basically required)
- [ ] Auto Data Typing for other columns (nice to have)

**Comment by geomodular** [comment]
The target column is checked for the ML task automatically for DAI and H2O-3. Also, there will be an argument to `model_build()` function to mark ML task explicitly in the next release.

Not sure for other columns now, but it's worth exploring. I added it to roadmap topics: https://github.com/h2oai/wave-ml/wiki/Roadmap#core-functionality

Closing issue.
