### ISSUE TITLE
Feedback: h2o_wave.ml

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave-ml#21]
Started here: `https://github.com/h2oai/wave/blob/feat/common-api/py/examples/h2o3.py` without reading extensive docs or anything, just feedback from initial usage. 

### System Setup
```
git clone https://github.com/h2oai/wave.git
cd wave
git fetch
git checkout feat/common-api

cd py
make setup

./venv/bin/pip install h2o
./venv/bin/pip install datatable

./venv/bin/pip install ipykernel
./venv/bin/python -m  ipykernel install

 ./venv/bin/jupyter notebook    

# Server is ./waved from the GitHub release 0.9.1 which is maybe the wrong thing to do?
```

### Notes
1. Inconsistency of data interactions
`build_model(train_path, target=target)` Build model requires a file path (pandas is not an option) but `predict = model.predict(test_df)` cannot take a path and has to be the actual data. I don't personally care which but all methods should take the same "type" of data whether that is a file path or data object

2. Example didn't work
I had data type issues when predicting with a datatable to tuple object: `predict = model.predict(test_dt.to_tuples()) `
```
OSError: Job with key $03017f00000132d4ffffffff$_93bf92eec9079a23639ed057aaa44ec3 failed with an exception: java.lang.IllegalArgumentException: Test/Validation dataset has categorical column 'Unemployment' which is real-valued in the training data
stacktrace: 
java.lang.IllegalArgumentException: Test/Validation dataset has categorical column 'Unemployment' which is real-valued in the training data
```
Switching to pandas fixed this but we should be careful with enum vs. numeric handling to avoid these types of errors

3. What makes this modeling package easier? 
I've only tried this one example at this point, but at this point I am not seeing why this is easier for me to use than "regular" AutoML. Perhaps it's more about when DAI is in the mix too.

4. We need to make visualizing easier.

```
page = site['/predictions']

n_train = 10
n_test = 10
n_total = n_train + n_test
v = page.add('example', ui.plot_card(
    box='1 1 4 5',
    title='Line',
    data=data('date price', n_total),
    plot=ui.plot([ui.mark(type='line', x_scale='time', x='=date', y='=price', y_min=0)])
))

# We are taking the last `n_train` values from the train set.
values_train = [(train_dt[-i, 'Date'], train_dt[-i, 'Fuel_Price']) for i in reversed(range(1, n_train + 1))]
values_test = [(test_dt[i, 'Date'], predict[i][0]) for i in range(n_test)]

v.data = values_train + values_test

page.save()
```
This is a lot. I am knew to the whole data buffers thing, but I can't just look at this and know how to use it on my data. It is going to take some time to sit-down and understand what `values_train` is so that I can figure out how to show data in cards how I want to. 

I personally see Predictions -> Wave App as the most important differentiator. Our customers can build models, let's make the "turn models into beautiful apps" part even easier. 

I will read the docs and do more work now, but initial thoughts

**Comment by geomodular** [comment]
Feedback and thread were very useful and served the purpose.

Closing, Thanks @mtanco and @lo5!
