### ISSUE TITLE
Support data inputs directly from memory

### ISSUE THREAD

**Issue by vopani** [h2oai/wave-ml#31]
It's more common to have the data for running or scoring a model in an app already present as a pandas dataframe 
(or similar format) in memory rather than as a file on disk.

It would help if there is also the option of inputting a pandas dataframe (I'd think this would cater to > 80% of cases) directly into WaveML functions rather than having to write them as csv files and then using the file paths.

This is for discussion as there are certainly more things to think about like other tabular data formats (H2O-Frame, datatable, etc.) and the pros/cons of supporting this (more dependency?).

**Comment by geomodular** [comment]
Closing as Pandas is integrated. There is room for other dataframes but let's create separate issues for the other options if a requirement emerges.
