### ISSUE TITLE
Allow DAI / Steam details to be specified in runtime

### ISSUE THREAD

**Issue by geomodular** [h2oai/wave-ml#39]
Currently, the Steam instances need to be specified using ENV variables. It's not flexible. We should have an option to be able to specify it during runtime.

## Goal
Provide a way to pass Steam instance names to `build_model()` function in order to use it for training. It might be useful to include some helper functions for Steam as well.

cc @AakashKumarNain

**Comment by vopani** [comment]
It might be useful to include typical utilities like fetching all DAI instances of a user, ability to launch a new DAI instance on the fly, terminating a DAI instance and so on. We can track each separately as well.

If all the steam capabilities can be supported, it can become seamless for a developer to stick to using WaveML for all ML requirements on cloud.

**Comment by AakashKumarNain** [comment]
`If all the steam capabilities can be supported, it can become seamless for a developer to stick to using WaveML for all ML requirements on cloud.` 

I think this is required if we really want devs to build apps solving complex use cases ASAP

**Comment by geomodular** [comment]
Thanks! Closing as the former goal has been fulfilled. Continuation here https://github.com/h2oai/wave-ml/issues/54
