### ISSUE TITLE
Look at the OSS Wave Apps for ML parts

### ISSUE THREAD

**Issue by geomodular** [h2oai/wave-ml#4]
## Goal

Check how the `H2O-3` in OSS Wave Apps are incorporated and see if it makes sense to use `wave-ml` library instead.

cc @mtanco

**Comment by vopani** [comment]
We should attempt to use it in the [credit risk](https://github.com/h2oai/wave-apps/tree/main/credit-risk) app, that's the only one as of now that uses H2O-3.

**Comment by mtanco** [comment]
https://github.com/h2oai/wave-apps/tree/main/insurance-churn-risk does too!

**Comment by vopani** [comment]
Ahh yes, so thats where I mixed up the predictor names by putting the Churn Predictor into the credit app!

**Comment by vopani** [comment]
Done here: https://github.com/h2oai/wave-apps/issues/41
