### ISSUE TITLE
Supporting all types of categorical conversion

### ISSUE THREAD

**Issue by vopani** [h2oai/wave-ml#45]
Categorical conversion is only possible from `int` and `string` columns and fails for real valued columns.

**Comment by vopani** [comment]
This still doesn't work properly. Will investigate.

**Comment by vopani** [comment]
Response from H2O-3 team:

`They need to be of the same type, it will not automatically convert between types. It is possible that your 2 cases differ because one of the variables is not used by the model at all. But your intuition is right - in the general case they should both fail`

**Comment by vopani** [comment]
@geomodular The only solution I can think of is to add `categorical_columns` as an argument to `.predict` and leave it to users to manage it correctly.

**Comment by geomodular** [comment]
I'm thinking of the actual state:
1. If the user uses DAI, there is no problem.
2. If the user prepares data in Pandas, there is no problem.

I don't like the idea of `.predict()` having non-intuitive arguments. If we introduce `categorical_columns` to `.predict()`, it might look it should be handled all the time.

So maybe another question here is, why we support `categorical_columns` if we have Pandas in place? Is it that useful to have it for `csv` files?

I'm just thinking aloud. If we have to we will use `categorical_columns` in `.predict()`.

**Comment by vopani** [comment]
`2. If the user prepares data in Pandas, there is no problem.` - this is not true.

```python
import pandas as pd
import h2o

df = pd.DataFrame({"x": [1, 2, 3], "y": ["1", "2", "3"], "z": ["ok", "ko", "ok"]})
h2o_df = h2o.H2OFrame(df)
```

When you have a variable like `z`, there is no issue, everything will work perfectly without even using `categorical_columns` since it's already a character column.

The issue is when you have a variable like `y`. Even though `y` is categorical in `df`, it is `numeric` in `h2o_df`. So it needs to be explicitly converted to a factor.

```python
>>> h2o_df["y"].isnumeric()
[True]
```

And such scenarios are very common in datasets (including the sample OSS apps that use WaveML), so its worth solving.

P.S. I really don't like adding `categorical_columns` to `.predict()` either, I agree it is very unnatural, unnecessary and unintuitive.

**Comment by vopani** [comment]
`the AutoML object as such doesn’t store it, the individual models do. You can lookup the properties of the individual model.` - from @michalkurka 

The MOJO download of the leader model contains the model metadata as a json file that does save the column types.
eg: (where I made the first column a factor)
```json
"column_types":["Enum","Numeric","Numeric","Numeric","Numeric","Numeric","Numeric","Numeric","Numeric","Numeric","Numeric","Numeric","Numeric","Numeric"]
```
