### ISSUE TITLE
Wave ML App for H2O AI Hybrid Cloud

### ISSUE THREAD

**Issue by vopani** [h2oai/wave-ml#50]
Publish an app (maybe a polished version of the wine example) that will be suitable for demo on cloud.

**Comment by geomodular** [comment]
We have a nice picture of grapes we can use for wine example. Thanks to @mtanco.

**Comment by vopani** [comment]
Initial implementation here: https://github.com/h2oai/wave-ml/tree/feat/h2o_wave_ml_app/h2o_wave_ml_app
This is WIP.

**Comment by vopani** [comment]
App for testing here: https://demo.h2o.ai/apps/1ab8afa9-7d5a-45b1-bac4-3e6e1061c45a

Few things to be ironed out before moving from demo to cloud. Will track separately if required.

**Comment by vopani** [comment]
First draft of final version is updated: https://github.com/h2oai/wave-ml/tree/feat/h2o_wave_ml_app/h2o_wave_ml_app

@geomodular 
I've tested this version on `cloud.h2o.ai` - all is working well.

@mtanco 
Once you share the app icon, this is ready to be published on public cloud.
