### ISSUE TITLE
Misclassification metric fails

### ISSUE THREAD

**Issue by vopani** [h2oai/wave-ml#55]
Misclassification isn't supported by H2O-3 and fails when used.
https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/algo-params/sort_metric.html

The reason of issue is likely because `sort_metric` and `stopping_metric` supports two different lists of metrics (which makes no sense to me if they are calculated anyway)

**Comment by geomodular** [comment]
I see; I haven't realized the two different lists. So if we want to preserve the current strategy of using the metrics, we should drop `misclassification` and `lift_top_group` to have an intersection. Or do it somewhat differently.

Thank you for catching this.

**Comment by vopani** [comment]
I think #56 can resolve all metric issues for now.
